export const invoicesListActions = {
  LOAD_INVOICES_START: 'LOAD_INVOICES_START',
  LOAD_INVOICES_SUCCESS: 'LOAD_INVOICES_SUCCESS',
  LOAD_MORE_INVOICES_SUCCESS: 'LOAD_MORE_INVOICES_SUCCESS',
  LOAD_INVOICES_ERROR: 'LOAD_INVOICES_ERROR',
  LOAD_INVOICE_START: 'LOAD_INVOICE_START',
  LOAD_INVOICE_SUCCESS: 'LOAD_INVOICE_SUCCESS',
  LOAD_INVOICE_ERROR: 'LOAD_INVOICE_ERROR',
}

export const userSettingsActions = {
  LOAD_USER_SETTINGS_SUCCESS: 'LOAD_USER_SETTINGS_SUCCESS',
  SET_USER_SETTINGS: 'SET_USER_SETTINGS',
  SET_USER_SETTING: 'SET_USER_SETTING',
}

// TODO: Separate by reducer
export default {
  USER_LOGIN_START: 'USER_LOGIN_START',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_SIGN_UP_START: 'USER_SIGN_UP_START',
  USER_SIGN_UP_SUCCESS: 'USER_SIGN_UP_SUCCESS',
  USER_SIGN_UP_ERROR: 'USER_SIGN_UP_ERROR',
  VERIFY_EMAIL_START: 'VERIFY_EMAIL_START',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_ERROR: 'VERIFY_EMAIL_ERROR',
  SEND_ACCOUNT_RECOVERY_EMAIL_START: 'SEND_ACCOUNT_RECOVERY_EMAIL_START',
  SEND_ACCOUNT_RECOVERY_EMAIL_SUCCESS: 'SEND_ACCOUNT_RECOVERY_EMAIL_SUCCESS',
  SEND_ACCOUNT_RECOVERY_EMAIL_ERROR: 'SEND_ACCOUNT_RECOVERY_EMAIL_ERROR',
  VERIFY_ACCOUNT_RECOVERY_TOKEN_START: 'VERIFY_ACCOUNT_RECOVERY_TOKEN_START',
  VERIFY_ACCOUNT_RECOVERY_TOKEN_SUCCESS: 'VERIFY_ACCOUNT_RECOVERY_TOKEN_SUCCESS',
  VERIFY_ACCOUNT_RECOVERY_TOKEN_ERROR: 'VERIFY_ACCOUNT_RECOVERY_TOKEN_ERROR',
  PASSWORD_CHANGE_START: 'PASSWORD_CHANGE_START',
  PASSWORD_CHANGE_SUCCESS: 'PASSWORD_CHANGE_SUCCESS',
  PASSWORD_CHANGE_ERROR: 'PASSWORD_CHANGE_ERROR',
  SEND_DIALOG_FLOW_TEXT_UTTERANCE_START: 'SEND_DIALOG_FLOW_TEXT_UTTERANCE_START',
  SEND_DIALOG_FLOW_TEXT_UTTERANCE_SUCCESS: 'SEND_DIALOG_FLOW_TEXT_UTTERANCE_SUCCESS',
  SEND_DIALOG_FLOW_TEXT_UTTERANCE_ERROR: 'SEND_DIALOG_FLOW_TEXT_UTTERANCE_ERROR',
}
